services:
  - type: web
    name: telegram-music-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_service.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: RENDER
        value: true
