services:
  - type: web
    name: telegram-music-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: BOT_TOKEN
        sync: false
      - key: RENDER
        value: true
      - key: KEEP_ALIVE_AGGRESSIVE
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: music-bot-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
