services:
  - type: web
    name: music-processing-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        sync: false
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: CELERY_BROKER_URL
        value: redis://localhost:6379
      - key: CELERY_RESULT_BACKEND
        value: redis://localhost:6379
      - key: CACHE_DIR
        value: "cache"
      - key: MAX_FILE_SIZE_MB
        value: "50"
      - key: COOKIES_FILE
        value: "cookies.txt"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8001"
